language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_install:
  - yes | sdkmanager "platforms;android-27"
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew test
  - ./gradlew assembleDebug